CREATE TABLE messages (
    id integer primary key generated by default as identity,
    room_id int NOT NULL,
    user_id int NOT NULL,
    content varchar NOT NULL,
    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW(),
    CONSTRAINT messages_room_id_fk FOREIGN KEY (room_id) REFERENCES public.rooms(id),
    CONSTRAINT messages_user_id_fk FOREIGN KEY (user_id) REFERENCES public.users(id)
);