CREATE TABLE users (
    id integer primary key generated by default as identity,
    username varchar NOT NULL,
    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW()
);