CREATE TABLE rooms (
    id integer primary key generated by default as identity,
    name varchar NOT NULL,
    created_at timestamp NOT NULL DEFAULT NOW(),
    updated_at timestamp NOT NULL DEFAULT NOW()
);